#ifndef __CONSTANTS_H
#define __CONSTANTS_H

extern const char *circlemud_version[];
extern const char *awakemud_version[];
extern const char *dirs[];
extern const char *exitdirs[];
extern const char *lookdirs[];
extern const char *fulldirs[];
extern const char *thedirs[];
extern const char *exit_bits[];
extern const char *genders[];
extern const char *thrdgenders[];
extern const char *posgenders[];
extern const char *position_types[];
extern const char *player_bits[];
extern const char *action_bits[];
extern const char *preference_bits[];
extern const char *affected_bits[];
extern const char *room_bits[];
extern const char *wear_bits[];
extern const char *extra_bits[];

extern const char *connected_types[];
extern const char *wear_where[];
extern const char *equipment_types[];
extern const char *item_types[];
extern const char *apply_types[];
extern const char *container_bits[];
extern const char *drinknames[];
extern const char *drinks[];
extern const char *color_liquid[];
extern const char *fullness[];
extern const char *npc_class_types[];
extern const char *weekdays[];
extern const char *month_name[];
extern int rev_dir[];
extern int drink_aff[][3];
extern size_t room_bits_count;
extern size_t action_bits_count;
extern size_t affected_bits_count;
extern size_t extra_bits_count;
extern size_t wear_bits_count;
extern const char *material_names[];
extern const char *barrier_names[];
extern const char *patch_names[];
extern const char *cyberware_names[];
extern const char *bioware_names[];
extern int material_ratings[];
extern int barrier_ratings[];
extern const char *attack_types[];
extern const char *wound_name[];
extern struct skill_data skills[];
extern const char *adept_powers[];
extern const char *gear_name[];
extern const char *attack_types[];
extern const char *spell_target[];
extern const char *wound_arr[];
extern struct spirit_table elements[4];
extern const char *foci_types[];
extern const char *shape_forms[];
extern const char *spell_wear_off_msg[];
extern struct spirit_table spirits[];
extern int convert_look[];
extern int convert_dir[];
extern const char *where[];
extern const char *hands[];
extern const char *wielding_hands[];
extern const char *color_liquid[];
extern const char *connected_types[];
extern const char *class_abbrevs[];
extern const char *npc_classes[];
extern const char *attack_types[];
extern const char *status_ratings[];
extern const char *short_where[];
extern const char *veh_type[];
extern const char *mod_name[];
extern const char *veh_aff[];
extern const char *veh_flag[];
extern const char *jurid[];
extern const char *host_type[];
extern const char *host_sec[5];
extern const char *intrusion[3];
extern const char *alerts[3];
extern const char *ic_type[];
extern const char *ic_option[];
extern const char *ic_option_long[];
extern const char *ammo_type[];
extern struct part_data parts[];
extern struct program_data programs[];
extern int attack_multiplier[];
extern const char *positions[];
extern int racial_limits[][2][6];
extern const char *attributes[];
extern struct drug_data drug_types[];
extern struct spell_types spells[];
extern const char *totem_types[];
extern const char *spell_category[5];
extern const char *spirit_name[];
extern const char *foci_type[];
extern const char *light_levels[];
extern const char *room_types[];
extern int damage_array[];
#endif
